---
title: "Milestone2"
author: "Chase Souder"
date: "2/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

"How Couples Meet and Stay Together" takes a really interesting topic and displays a wide variety of related data points in an easy to navigate manner. The data is organized very logically, and every graph/chart is placed under a title and tab which makes it very clear what you're looking at. My first main criticism would be the lack of color; on the whole, it's pretty bland to look at. I wish the coder would have changed the color schemes a bit to provide some pop. The other main drawback for me is that a few data sets are not displayed in a way that makes relationship between factors as clear as possible. For example, "Educational Attainment" and, to a lesser degree, "Political Affiliation" make it more difficult to quickly determine correlation between variables by using the grid format as opposed to a scatter plot with a line of best fit.

"Fingerprints of Colonization" does a good job of incorporating a multitude of different factors in its analysis of the effects of colonization. The ability to remove certain colonizers from the first graph of each section is a helpful feature. However, when doing this, sometimes the colors of groups change, which can be a bit confusing and decreases the clarity of the graph. Another problem is simply that the graphs are too full; with so many countries, it's very difficult to actually track any one across the entirety of the x axis. My final issue with this project is that it isn't really clear what, if any, correlation it is attempting to display. There aren't any trends that really jump out at me, besides a generalized increase of all factors over time, so a section explaining the results may have been helpful.


